syntax on
filetype plugin indent on
set path=.,**
set tags+=$CTAGS
set clipboard=unnamedplus
set nocompatible
set relativenumber
set tabstop=4 softtabstop=4
set shiftwidth=4
set expandtab
set autoread
set smartindent
set autochdir
set nu
set nowrap
set linebreak
set smartcase
set noswapfile
set nobackup
set incsearch
set laststatus=2
set noshowmode
set colorcolumn=80
set foldmethod=indent
set foldlevelstart=99
set foldnestmax=2
set foldminlines=1

" I'll have to test this against other environments sometime in the future
if $TERM == 'xterm-kitty'
    " use terminal background
    set t_ut= 
    " fix to strange garbage characters getting displayed when
    " opening up certain buffers
    set t_RV=
    colorscheme mycolors
endif

augroup vimrc
    au!
    " center the screen upon entering insert mode
    au InsertEnter * normal zz
augroup END

runtime plugins.vim
runtime keybinds.vim
