#!/usr/bin/sh

if command -v pacman >/dev/null 2>&1; then
    alias search="pacman -Ss"
    alias update="sudo pacman -Syu"
    alias install="sudo pacman -S"
    alias uninstall="sudo pacman -Rns"
    alias query="pacman -Qi"
elif command -v apt-get >/dev/null 2>&1; then
    alias search="apt-cache search"
    alias update="sudo apt-get update && apt-get upgrade"
    alias install="sudo apt-get install"
    alias uninstall="sudo apt-get --purge autoremove"
fi

if command -v bat >/dev/null 2>&1; then
    alias cat="bat --paging=never"
    alias view="bat"
else
    alias view="less"
fi

if command -v zoxide >/dev/null 2>&1; then
    eval "$(zoxide init zsh)"
    alias cd="z"
fi

alias dark-theme="cd ~/.home/colorscheme && ./install.py && cd - >/dev/null"
alias light-theme="cd ~/.home/colorscheme && ./install.py -t=light && cd - >/dev/null"

alias home="cd ~/.home"
alias aliases="vim ~/.config/zsh/aliases && unalias -m '*' && source ~/.config/zsh/aliases"
alias functions="vim ~/.config/zsh/functions && source ~/.config/zsh/functions"
alias vimrc="vim ~/.vim/vimrc"
alias zshrc="vim ~/.config/zsh/.zshrc && source ~/.config/zsh/.zshrc"
alias packages="vim ~/.home/packages"

alias .env="source .devenv"
alias gcl="git clone"
alias gs="git status"
alias gc="git commit"
alias gcm="git commit -m"
alias ga="git add"
alias gau="git add -u"
alias gd="git diff"

alias clean="make clean"

alias mkexe="chmod +x"

alias venv=". venv/bin/activate"
alias tdd="python ~/dev/autotest/tdd.py"
alias gamelib="cd ~/dev/gamelib && source .env"
alias gamelib-black="gamelib && black gamelib && black tests"
alias gamelib-tdd="gamelib && tdd tests gamelib"
alias gamelib-install="gamelib && pip install ."
alias gamelib-ipython="gamelib-install && clear && ipython"
alias peffjepin.com="cd ~/dev/portfolio && venv"

alias pytree="tree -I __pycache__ -I dist -I build -I *.egg-info"
alias pyclean="rm -rf *.egg-info build dist"

alias lsa="ls -lah --color=auto"
alias ls="ls --color=auto"
alias ..="cd .."
alias ..2="cd ../.."
alias ..3="cd ../../.."
alias ..4="cd ../../../.."

alias wttr="curl wttr.in/"
